### PR TITLE
[Fixed]Missing asterisk for required fields Register Backends form

### LINKED ISSUE #40: Required fields in the Register Storage Backends form are not marked with asterisk
### What is the Issue?
The **_Register Storage Backends_** form in the Home component has all fields `required`.  
Not filling or selecting any of the fields throws a validation error.  
The form field labels do not have any indication as to which fields are required (all the fields in this form are required)  

### How can it be fixed?
Add an `asterisk(*)` or the word `required` alongwith the label of the form field.

### PR DESCRIPTION
**Pull request by anvithks**
### What does this PR do?
The required fields in the _**Register Storage Backends**_ form in the home component are marked with a red `asterisk(*)` next to the form label.  

### What issue does this PR fix, if any?
Fixes #40

### CODE REVIEW

**Comment by leonwanghui** [comment]
@anvithks Please address the ci error.

**Comment by anvithks** [comment]
@leonwanghui Seems like my changes have either been overwritten or another PR is conflicting. 
I think it is some other PR #39 that was breaking the CI. I can some duplicate changes there. 

Could you please run the CI again?

**Comment by anvithks** [comment]
@leonwanghui can we trigger the CI by using any automation commands?

**Comment by anvithks** [comment]
@leonwanghui Please review and merge.

**Pull request merged**
