### PR TITLE
support IBM cloud object storage from the dashboard

### PR DESCRIPTION
**Pull request by acorbellini**
I have added support for IBM Cloud Object Storage (COS) in multi-cloud, but found that the dashboard didn't pick it up automatically. So I made the modifications needed to add support for COS in the dashboard. 
I have included some modifications to the Dockerfile script, removing an unnecessary copy (although I wanted to remove the need to update all the image file layers when you modify a single file, like entrypoint.sh).
I modified entrypoint.sh to support the new version of nginx, which moves the configurations to /etc/nginxs/conf.d. Probably, the first echo and the last cat of the file could be removed.
Finally, I added the svg logo for COS.

### CODE REVIEW

**Comment by xing-yang** [comment]
Thanks @acorbellini !  We'll take a look.

**Comment by xing-yang** [comment]
@wisererik Can you ask zhangpengchong to take a look?

**Comment by wisererik** [comment]
@xing-yang  @acorbellini Sure

**Comment by jimccfun** [comment]
@wisererik @acorbellini 
There is no problem with the modified parts, but two files[home.component.ts/home.component.html] need to be modified so that they can be displayed on the home page.

**Comment by leonwanghui** [comment]
@acorbellini Well done!

**Comment by leonwanghui** [comment]
@jimccfun I have assigned u the write access, then u can merge it after it's LGTY.

**Comment by acorbellini** [comment]
@jimccfun I have modified the home component to show the ibm cos cloud

**Pull request merged**
